export type RaisecType = 'R' | 'A' | 'I' | 'S' | 'E' | 'C';

export interface Question {
  id: string;
  text: string;
  category: 'RAISEC' | 'ACADEMIC' | 'PREFERENCE';
  raisecType?: RaisecType;
  options?: { label: string; value: number | string }[];
  type: 'likert' | 'single-choice' | 'multi-choice' | 'ranking';
}

export interface UserInfo {
  fullName: string;
  email: string;
  phone: string;
  grade: string;
  city: string;
}

export interface UserResponses {
  raisec: Record<string, number>; // questionId -> value (1-5)
  academic: {
    favoriteSubject: string;
    strongestSubject: string;
    examPrep: string;
    learningStyle: string;
    engineeringGoal: string;
  };
}

export interface Branch {
  id: string;
  name: string;
  description: string;
  weights: {
    [key in RaisecType]?: number;
  } & {
    math?: number;
    physics?: number;
    chemistry?: number;
    cs?: number;
    logic?: number;
  };
}

export interface ScoredBranch {
  branch: Branch;
  score: number;
  matchReason: string;
}

export interface AnalysisResult {
  topBranches: ScoredBranch[];
  raisecProfile: { type: RaisecType; score: number }[];
  dominantType: string;
  aiInsight?: string; // Generated by Gemini
}